### ISSUE TITLE
Fix term field to use slug instead of name in all templates

### ISSUE THREAD

**Issue by seanvandermolen** [bootscore/bs-grid#38]
According to the instructions on the plugin page, you're supposed to use the term slug... however in the query, the field is set to 'name' instead of 'slug' so unless the term name matches the slug nothing is returned.

```php    
$options['tax_query'] = array(array(
      'taxonomy' => $tax,
      'field'    => 'name',
      'terms'    => $terms,
```

**Comment by crftwrk** [comment]
Ops, you're absolutely right. Thank you for pointing this out. Are you able to fix this and create a pull request? If so, we need this to fix in https://github.com/bootscore/bs-swiper as well.
