### ISSUE TITLE
BS-Grid should not list private pages

### ISSUE THREAD

**Issue by alexarcherr** [bootscore/bs-grid#43]
Hello! am I right in decision that BS-Grid should exclude pages and posts marked 'private'?

As I read in WP documentation, private post is blocked from the public. Those with the right user access are able to see the private post if they log into the WordPress dashboard.

**Comment by crftwrk** [comment]
Hello,

plugin does exactly what it should:

- Private posts are hidden in the frontend loop for visitors
- If you are logged in as an admin, private posts are visible in the loop for admins and marked as private

Nothing wrong here?

**Comment by alexarcherr** [comment]
Thank you! Really, I was logged in as an admin.

**Comment by crftwrk** [comment]
You‘re welcome 👍
